// Database Models - Export all from localDb
export {
  getProviderConnections,
  getProviderConnectionById,
  createProviderConnection,
  updateProviderConnection,
  deleteProviderConnection,
  deleteProviderConnections,
  getProviderNodes,
  getProviderNodeById,
  resolveProviderNodeForConnection,
  createProviderNode,
  updateProviderNode,
  deleteProviderNode,
  deleteProviderConnectionsByProvider,
  getModelAliases,
  setModelAlias,
  deleteModelAlias,
  deleteModelAliasesForProvider,
  getMitmAlias,
  setMitmAliasAll,
  getApiKeys,
  createApiKey,
  deleteApiKey,
  validateApiKey,
  isCloudEnabled,
  resolveProxyForProvider,
  getHiddenModelsByProvider,
  // key_pool — per-provider reserve API key pool (auto-replace + manual pull/push)
  getPoolKeys,
  getPoolKeysPaged,
  getPoolCount,
  addKeysToPool,
  removeKeyFromPool,
  pullKeysFromPool,
  createPoolConnections,
  moveConnectionsToPool,
} from "@/lib/localDb";
